[package]
name = "gardum"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
bevy = { version = "0.6", default-features = false, features = ["render", "x11"] }
bevy_egui = { version = "0.11", default-features = false, features = ["multi_threaded"], optional = true }
heron = { version = "1.1", features = ["3d"] }
leafwing-input-manager = "0.2"
clap = { version = "3.0", features = ["derive"] }
derive_more  = { version = "0.99", default-features = false, features = ["deref", "deref_mut", "from"] }
strum = { version = "0.23", features = ["derive"] }

[dev-dependencies]
approx = "0.5"

[features]
default = ["client"]
client = ["bevy/png", "bevy_egui"]
