name: Main
on:
  push:
    branches-ignore:
      - "releases/**"
    paths-ignore:
      - "**.md"
      - ".gitignore"
  pull_request:
    paths-ignore:
      - "**.md"
      - ".gitignore"
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Cache crates
        uses: Swatinem/rust-cache@v1

      - name: Test
        uses: actions-rs/tarpaulin@v0.1

      - name: Upload code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: cobertura.xml

  Clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Cache crates
        uses: Swatinem/rust-cache@v1

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  Format:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  Codecov:
    needs: [Test, Clippy, Format]
    runs-on: ubuntu-latest
    steps:
      - name: Download code coverage results
        uses: actions/download-artifact@v2
        with:
          name: code-coverage-report

      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
