name: Main
on:
  push:
    branches-ignore:
      - "releases/**"
    paths-ignore:
      - "**.md"
      - ".gitignore"
  pull_request:
    paths-ignore:
      - "**.md"
      - ".gitignore"
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Cache crates
        uses: Swatinem/rust-cache@v1

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

  Clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Cache crates
        uses: Swatinem/rust-cache@v1

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  Format:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
